version: '3'

services:
  consumer:
    build:
      dockerfile: Dockerfile.consumer
      context: .
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017/david19
      CONSUMER_PORT: 8081
      CONSUMER_METRICS_PORT: 8082
      ELASTIC_NODE_URL: https://af9d320d7f6b4034aa0e745027177116.us-east1.gcp.elastic-cloud.com:9243/
      ELASTIC_API_KEY: J5uroNDJV88RdtKDQE6sQL8z
      ELASTIC_CONSUMER_INDEX: david19-consumer
      LOGGER_LEVEL: debug
    networks:
      - default

  api:
    build:
      dockerfile: Dockerfile.api
      context: .
    ports:
      - "8080:8080"
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017/david19
      API_PORT: 8080
      API_METRICS_PORT: 8082
      ELASTIC_NODE_URL: https://af9d320d7f6b4034aa0e745027177116.us-east1.gcp.elastic-cloud.com:9243/
      ELASTIC_API_KEY: J5uroNDJV88RdtKDQE6sQL8z
      ELASTIC_API_INDEX: david19-api
      LOGGER_LEVEL: debug
    networks:
      - default

  seeder:
    build:
      dockerfile: Dockerfile.seeder
      context: .
    networks:
      - default

  mongo:
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    volumes:
      - ./tmp:/data/db
    networks:
      - default
